### ISSUE TITLE
TypeError: GetSigma.calc_sigma() missing 1 required positional argument: 'model'

### ISSUE THREAD

**Issue by freemde23** [ExponentialML/ComfyUI_ELLA#18]
ComfyUI Upgraded to the latest version
But this node cannot find the 'model'. where is the model installed for this node? 
or can other nodes be used to replace it?
![2024-04-15_162111](https://github.com/ExponentialML/ComfyUI_ELLA/assets/122530501/ea1241a0-4a09-4753-b6be-58b2851f0868)

**Comment by FNSpd** [comment]
Are you sure you plugged your Stable Diffusion model into Get Sigma node?

**Comment by freemde23** [comment]
@FNSpd how to fix ComfyUI  Error ?: GetSigma.calc_sigma() missing 1 required positional argument: 'model'

**Comment by FNSpd** [comment]
Take your normal model from Load Checkpoint and plug it into Get Sigma
